name: watchlist_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/book_cover.jpeg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
    - family: FamilleIcons
      fonts:
        - asset: assets/fonts/FamilleIcons.ttf